### ISSUE TITLE
Unable to find resource ID #0xb

### ISSUE THREAD

**Issue by it3r4-pineda** [triniwiz/nativescript-youtubeplayer#18]
An uncaught Exception occurred on "main" thread.
android.content.res.Resources$NotFoundException: Unable to find resource ID #0xb
	at android.content.res.Resources.getResourceName(Resources.java:2235)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:968)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
	at android.app.BackStackRecord.run(BackStackRecord.java:793)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:482)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by triniwiz** [comment]
Fixed on `@triniwiz/nativescript-youtubeplayer`
