### ISSUE TITLE
Nativescript Angular giving No view found error

### ISSUE THREAD

**Issue by rg777** [triniwiz/nativescript-youtubeplayer#27]
I am getting the following error for android when running on android.

```
System.err: java.lang.IllegalArgumentException: No view found for id 0x9 (unknown) for fragment YouTubePlayerFragment{5dd3ce #4 id=0x9 TNSYoutubeFragment}
System.err: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1271)
System.err: 	at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2407)
System.err: 	at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2186)
System.err: 	at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2142)
System.err: 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2043)
System.err: 	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:719)
System.err: 	at android.os.Handler.handleCallback(Handler.java:790)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
System.err: 	at android.os.Looper.loop(Looper.java:164)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by rg777** [comment]
Cleaning and installing the android platform again solved the problem.
